- hosts: localhost
  become: yes
  tasks:



   - name: "Install java"
     apt:
             name: openjdk-11-jdk
             state: present     



   - apt_key:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
        state: present



   - name: add this key to another list
     command: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/  > /etc/apt/sources.list.d/jenkins.list'

   - name: Update apt-get repo and cache
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  

   - name : install jenkins
     command: sudo apt install jenkins -y
   
   - name: start jenkins
     command: sudo systemctl start jenkins
